### ISSUE TITLE
"Provide Feedback" on demo not working

### ISSUE THREAD

**Issue by k3n** [intridea/houston#5]
Chrome 34 on Win7.

When I click the button, a white modal pops-up with a processing animation that soon disappears, but the box remains empty. At this point, nothing on the page works and I'm forced to refresh.

Opening the console, I see the following:

```
Uncaught SecurityError: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document. batch.js:466
Uncaught TypeError: Cannot read property 'extend' of undefined jira.webresources:user-pickers.js:6
Uncaught Error: jira/field/issue-picker missing jira/ajs/select/multi-select batch.js:338
Uncaught TypeError: Cannot read property 'Renderers' of undefined com.atlassian.jira.collector.plugin.jira-issue-collector-plugin:form-collector.js:2
```

**Comment by janv8000** [comment]
See [Issue collector doesn't work without access to sessionStorage](https://jira.atlassian.com/browse/JRA-40251)
